'''
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '8,28,48 * * * *'
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use a Secret in the Workflow
      env:
          URL: ${{ secrets.URL }}
      run: |
          echo "My URL is $URL"
          
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Print rootdir
      run: |
        echo "rootdir: $(pwd)"
    - name: Run tests
      run: |
        pytest -k test_lanes
        
'''
